/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Examplegradle;





import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test
    public void canConstructAPersonWithAName() {
    
    }
}